# Generated by Django 3.1 on 2020-08-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extemp', '0002_auto_20200827_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='code',
            field=models.CharField(default='USX', max_length=10),
            preserve_default=False,
        ),
    ]
