# Generated by Django 3.1 on 2020-08-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extemp', '0003_event_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='code',
            field=models.CharField(default='R1', max_length=10),
            preserve_default=False,
        ),
    ]
