# Generated by Django 3.1 on 2020-08-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extemp', '0006_auto_20200828_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicinstance',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
