# Generated by Django 3.1 on 2020-08-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extemp', '0007_topicinstance_modified_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicinstance',
            old_name='modified_date',
            new_name='modified',
        ),
    ]
