# Generated by Django 3.1 on 2020-08-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extemp', '0008_auto_20200828_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
