# Generated by Django 3.1 on 2020-08-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extemp', '0010_auto_20200829_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicinstance',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
