# Generated by Django 3.1 on 2020-08-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extemp', '0011_topicinstance_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='open',
        ),
        migrations.AddField(
            model_name='section',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
