# Generated by Django 3.1 on 2020-08-29 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extemp', '0013_auto_20200829_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundgroup',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='extemp.tournament'),
            preserve_default=False,
        ),
    ]
