# Generated by Django 3.1 on 2020-10-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extemp', '0017_auto_20201016_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
