# Generated by Django 3.1 on 2020-10-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extemp', '0018_round_current'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoundGroup',
        ),
    ]
